### ISSUE TITLE
Globals and Templated Defaults

### ISSUE THREAD

**Issue by adamrdrew** [adamrdrew/nasti#8]
One feature cookiecutter has that NASTI lacks is the ability to reference one or more strings in a template and then apply transformations on them. I think I know how to implement that. We'd extend the nastifile with two new features: globals and templated defaults. It would look something like this:

```yaml
---
globals:
    - name: "app_name"
      prompt: "App Name"
      help: "The name of the app"
      default: "My App"
    - name: "version"
      prompt: "Version"
      help: "The API Version"
      default: "v1"
mutations:
  - name: "route_slug"
    prompt: "Route Slug"
    help: "Slug used for the route"
    replace: "template_route"
    default: "{{app_name|lower|replace(' ', '_')}}{{version}}_route"
    files:
      - "local_config.json"
    validation:
      kind: "slug"
```

Defaults would be default values the mutations would use if you don't enter anything. Defaults could be a straight string value or could use template syntax like what cookiecutter uses, including that little DSL for transformations. Globals would be addressable by name in the deftault templates and would be prompted for user input before mutations.
